G04 Layer: TopLayer*
G04 EasyEDA v6.5.9, 2022-08-01 21:18:00*
G04 ac5e******************************************aa,10*
G04 Gerber Generator version 0.2*
G04 Scale: 100 percent, Rotated: No, Reflected: No *
G04 Dimensions in millimeters *
G04 leading zeros omitted , absolute positions ,4 integer and 5 decimal *
%TF.GenerationSoftware,KiCad,Pcbnew,(6.0.6)*%
%TF.CreationDate,2022-09-22T21:47:13+08:00*%
%TF.ProjectId,Stealthburner_Toolhead_PCB,53746561-6c74-4686-9275-726e65725f54,rev?*%
%TF.SameCoordinates,Original*%
%TF.FileFunction,NonPlated,1,6,NPTH,Drill*%
%TF.FilePolarity,Positive*%
%FSLAX46Y46*%
G04 Gerber Fmt 4.6, Leading zero omitted, Abs format (unit mm)*
G04 Created by KiCad (PCBNEW (6.0.6)) date 2022-09-22 21:47:13*
%MOMM*%
%LPD*%
G01*
G04 APERTURE LIST*
%TA.AperFunction,ComponentDrill*%
%ADD10C,3.000000*%
%TD*%
G04 APERTURE END LIST*
D10*
%TO.C,J9*%
X133451600Y-118561600D03*
%TO.C,J1*%
X143766000Y-105206800D03*
M02*
